Jdp231101 2
piotr-grosicki/project-jdp-2311-01 pull request #3
Opened 2023-10-21 07:37 UTC by salata123

Code review for:
[JDP-2311-01]
GroupController - wstępna implementacja endpointów

2023-10-21 08:31 UTC, NickiRafal commented
> Recenzja kodu dla: [JDP-2311-01] GroupController - wstępna implementacja endpointów

Testowałeś metodę createGroup w Postmanie? Wydaje mi się że ta metoda nie zadziała. W tej metodzie próbujesz odebrać trzy parametry groupId, groupNameToAdd, i groupDescriptionToAdd. Jednak metoda @RequestBody służy do przekazywania ciała z żądania HTTP jako obiektu, a nie do odbierania trzech oddzielnych parametrów. Możesz stworzyć klasę DTO (Data Transfer Object) do przesyłania tych danych, a następnie odbierać ją w jednym obiekcie.

2023-10-21 12:17 UTC, salata123 commented
> > Recenzja kodu dla: [JDP-2311-01] GroupController - wstępna implementacja endpointów
> 
> Testowałeś metodę createGroup w Postmanie? Wydaje mi się że ta metoda nie zadziała. W tej metodzie próbujesz odebrać trzy parametry groupId, groupNameToAdd, i groupDescriptionToAdd. Jednak metoda @requestbody służy do przekazywania ciała z żądania HTTP jako obiektu, a nie do odbierania trzech oddzielnych parametrów. Możesz stworzyć klasę DTO (Data Transfer Object) do przesyłania tych danych, a następnie odbierać ją w jednym obiekcie.

Zmieniłem wymagania w requeście, przetestowałem na szybko postmanem i otrzymałem poprawną odpowiedź

2023-10-21 12:28 UTC, NickiRafal commented
Wydaje mi się że nie zadziała to z bazą danych ale ok. Dojdziemy do tego.

2023-10-21 12:36 UTC, salata123 commented
> Wydaje mi się że nie zadziała to z bazą danych ale ok. Dojdziemy do tego.

No to na pewno nie zadziała z bazą danych, ale miało zwracać sztuczne dane, więc na razie zwraca. Będzie do zmiany, jak już będzie zaimplementowana encja itp

2023-10-21 15:30 UTC, piotr-grosicki requested changes
konflikty: https://www.jetbrains.com/help/idea/resolve-conflicts.html

2023-10-22 07:12 UTC, piotr-grosicki requested changes
dwa razy dodany group controller

2023-10-22 21:26 UTC, closed without merging